routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('cruds','CrudController');
Route::post('/upload/{id}','CrudController@update');

// Route::get('/index','CrudController@index');
// Route::post('/store','CrudController@store');
// Route::get('/show','CrudController@show');
// Route::post('/delete/{id}','CrudController@destroy');

app/Crudimage.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Crudimage extends Model
{
    protected $fillable = ['fstName','lstName','image'];
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/CrudController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\File;
use Illuminate\Pagination\Paginator;
use App\Crudimage;
use Validator;
// use App\User;
use Storage;

class CrudController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // $crud = Crudimage::all();
        // return view('index', compact('crud'));
        return view('index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {   
        //Validation rules Starts here -->
        // $rules =array(
        //     'fstName'=>'required',
        //     'lstName'=>'required',
        //     'img'=>'required|max:2048|mimes:jpg',
        // );

        // $messages = array(
        //     'img.mimes' => 'select file type " .jpg only "',
        //     'img.max' => 'select a file upto 2mb ',
        // );

        // $validator = Validator::make($request->all(), $rules,$messages);
        //     //Check to see if validation fails or passes
        // if($validator->fails())
        // {
        //     // Alert::error('Error','Somthing went wrong.. Please check errors..! ');
        //     return redirect()->back()->withErrors($validator)->withInput();
        // }

        $crud = new Crudimage();
        $crud->fstName = $request->fst;
        $crud->lstName = $request->lst;
        if ($request->file('img')) {
            $upldFile = $request->img;
            $extension = $upldFile->getClientOriginalExtension();
            $filename = $upldFile->getFilename().'.'.$extension;
            Storage::disk('local')->put('public/uploads/'.$filename, File::get($upldFile));
            
            $crud->image = $filename;
        }
            $crud->save();
        return redirect('/cruds')->with('success','User with Image has been added..!');
    }


    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show()
    {
        $crud = Crudimage::get(); //->paginate(5);
        return view('show', compact('crud'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = Crudimage::find($id);
        return view('edit',compact('data','id'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data = Crudimage::findOrFail($id);
        $data->fstName = $request->fst;
        $data->lstName = $request->lst;
        
        if ($request->file('img')) {
            
            $upldFile = $request->img;
            $extension = $upldFile->getClientOriginalExtension();
            $filename = $upldFile->getFilename().'.'.$extension;
            Storage::disk('local')->put('public/uploads/'.$filename, File::get($upldFile));
            
            //delete old image
            // $oldFilename=$data->image;
            $mult[] = $filename;
            $data->image = json_encode($mult);
            // $aboutus->image=$filename;
            // Storage::delete($oldFilename);
        }
            $data->save();
        return redirect('/cruds/show')->with('success','User with Image has been updated..!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        // return ($id);
        $crud = Crudimage::findOrFail($id);
        // $path = storage_path('public/uploads/'. $crud->image);
        // if(file_exists($path))
        // {
        //     unlink($path);
        // }
        $crud->delete();
        return redirect()->back()->with('success', 'User is successfully deleted');

    }
}

resources/views/edit.blade.php
<!DOCTYPE html>
<html>
<head>
	<title>Upload Image</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">

	<!-- jQuery library -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

	<!-- Latest compiled JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
</head>
<body>
	<div class="container" >
		<div class=" row col-md-8">
		<!-- <form action="{{route('cruds.update', $data->id)}}" method="PATCH" enctype="multipart/form-data"> -->
		<form action="/upload/{{ $data->id }}" method="POST" enctype="multipart/form-data">
			@csrf
			<!-- {{ method_field('PATCH') }} -->
			<h2>Image Upload</h2>
			<div class="form-group">
				<label>First Name :</label>
				<input type="text" name="fst" class="form-control" value="{{$data->fstName}}" required autofocus>
			</div><br/>
			<div class="form-group">
				<label>Last Name :</label>
				<input type="text" name="lst" class="form-control" value="{{$data->lstName}}" required autofocus>
			</div><br/>
			<div class="form-group">
				<img src="{{Storage::url('uploads/'. $data->image)}}" width="70" height="70"><br/>
				<label>Upload Image :</label>
				<input type="file" name="img" required autofocus>
			</div><br/>
			<button type="submit" class="btn btn-primary">Update</button>
			<!-- <div class="form-group">
				<input type="submit" class="btn btn-primary" >  -->
			<!-- </div> -->
		</form>
		</div>
	</div>
</body>
</html>

resources/views/index.blade.php
<!DOCTYPE html>
<html>
<head>
	<title>CRUD IMAGE OPERATION</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">

	<!-- jQuery library -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

	<!-- Latest compiled JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
</head>
<body>
	<div class="container"  >
			<div class="col-md-8 offset-md-2">
			@if ($errors->any())
		          <div class="alert alert-danger">
		              <ul>
		                  @foreach ($errors->all() as $error)
		                      <li>{{ $error }}</li>
		                  @endforeach
		              </ul>
		          </div>
		      @endif
		    </div>	
		<div class=" row col-md-6">
		<form action="{{route('cruds.store')}}" method="post" enctype="multipart/form-data">
			@csrf
			<h2 style="text-align: center;">Image Upload</h2>
			<div class="form-group">
				<label>First Name :</label>
				<input type="text" name="fst" class="form-control" required autofocus>
			</div><br/>
			<div class="form-group">
				<label>Last Name :</label>
				<input type="text" name="lst" class="form-control" required autofocus>
			</div><br/>
			<div class="form-group">
				<label>Upload Image :</label>
				<input type="file" name="img" autofocus >
			</div><br/>
			<div class="form-group">
				<input type="submit"  class="btn btn-primary" > 
				<a href="/cruds/show" target="_blank" class="btn btn-primary" style="float: right;" > Details </a>  
			</div>
		</form>
		</div>
	</div>
</body>
</html>

resources/views/show.blade.php
<!DOCTYPE html>
<html>
<head>
	<title>Upload Image</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">

	<!-- jQuery library -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

	<!-- Latest compiled JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
</head>
<body>
	<div class="card ">
	  <div class="card-header">
	  
	  </div>
	  <div class="card-body">
	    @if ($errors->any())
	      <div class="alert alert-danger">
	        <ul>
	            @foreach ($errors->all() as $error)
	              <li>{{ $error }}</li>
	            @endforeach
	        </ul>
	      </div><br />
	    @endif
	<div class="Container ">
		<div class="col-md-12 justify-content-center">
		<div class="col-md-10" style="margin-left: 80px;" >
			<h2 style="text-align: center;">Record Details</h2>
			<a href="/cruds" class="btn btn-primary" style="float: left;">Create Page</a>
			<br/><br/>
			<table class="table table-bordered table-striped" style="text-align: center;" >
				<tr>
					<th style="text-align: center;">No.</th>
					<th style="text-align: center;">First Name</th>
					<th style="text-align: center;">Last Name</th>
					<th style="text-align: center;">Profile</th>
					<th style="text-align: center;">Action</th>
				</tr>
				<?php $i = 1;  ?>
				@foreach($crud as $prof)
				<tr>
					<td>{{ $i }}</td>
					<td>{{$prof->fstName}}</td>
					<td>{{$prof->lstName}}</td>
					<td><img src="{{Storage::url('uploads/'. $prof->image)}}" style="height: 70px; width: 70px; border-radius: 50px;" alt="picture"></td>
					<td><form action="{{ route('cruds.destroy', $prof->id)}}" method="post">
						<a href="{{route('cruds.edit', $prof->id)}}" class="btn btn-primary">Edit</a>
		                  @csrf
		                  <!-- @method('DELETE') -->
		                  <button class="btn btn-primary" type="submit" >Delete</button>
		                </form>
					</td>
				</tr>
				<?php $i++; ?>
				@endforeach
			</table>
		</div>
		</div>
	</div>
</body>
</html>